apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: naughty-coral-marlin
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: naughty-coral-marlin 
  name: naughty-coral-marlin
  namespace: flacatus-test
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: naughty-coral-marlin 
